name: Fetch YouVersion Moments

on:
  schedule:
    # Runs daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  fetch-moments:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Create .env file with secrets
      run: |
        echo "ONEMIN_AI_API_KEY=${{ secrets.ONEMIN_AI_API_KEY }}" > .env
        echo "YOUVERSION_BEARER_TOKEN=${{ secrets.YOUVERSION_BEARER_TOKEN }}" >> .env
        
    - name: Run complete moments pipeline
      run: |
        cd scripts
        python fetch_moments.py  # This now includes Bible texts and AI tags
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add moments.json
        if ! git diff --cached --exit-code > /dev/null; then
          git commit -m "Update moments $(date)"
          git push
        else
          echo "No changes to commit"
        fi
